### ISSUE TITLE
Understand your code.

### ISSUE THREAD

**Issue by DarXT3mpla4** [dataplayer12/homesecurity#2]
Hello,

I was reading about your project which I really like, I am a computer science student and I enjoy creating things with IoT devices especially the Pi, however I never used the Jetson before or anything related to neural network or machine learning. I feel like your project would help me learn how I can use that, I would appreciate if you can get me up to speed on your files structure so I understand what each file does and if you can provide me with some comments, that would be so much appreciated

**Comment by dataplayer12** [comment]
Hi @Venum77 
Thank you for your interest in this repo. As I wrote in the readme, this work was born out of the security needs of my family. As such, this repo is less flashy in terms of features and more oriented towards creating a practical security system. So, if you don't have a background in machine learning or neural networks, this is not the best place to start. 

I would recommend using another one of my projects called ShaveNet. This project allows you to collect your own data and apply machine learning in a very easy to understand way. Another project is facial-recognition, which it seems you are already aware of.

For this repo, I would like to state two things:

1. If you like to use raspberry pi, please start by reading the code related to raspberry pi 3. The code provides a good example of multi-threading and computer vision concepts.
2. I realize that as it stands, the code, especially that related to jetson nano and tx2, requires a lot of good documentation to make good use of this repo. I will keep updating the readme for each part of the code. I will keep your issue open for now. Please remind me if I forget to update the documentation.

**Comment by dataplayer12** [comment]
Hi @DarXT3mpla4 

I have added a lot of instructions on how to install the dependencies and setup the required details for jetson nano and raspberry pis. Unless someone has specific requests, I believe the current documentation does a reasonable job of explaining how to get everything up and working. Thus, I am closing your issue. Feel free to open it in case you don't understand the instructions.
