### ISSUE TITLE
Tf error

### ISSUE THREAD

**Issue by flaryx32** [dataplayer12/homesecurity#20]
~/homesecurity$ bash launch.sh                                        bash: launch.sh#!/bin/bash: No such file or directory                                           Traceback (most recent call last):                File "jetsonano/securitycamnano.py", line 11, in <module>                                         from file_managernano import FileManagerThread, FileCleanerThread, counter                    File "/home/flaryx32/homesecurity/jetsonano/file_managernano.py", line 6, in <module>             import human_detect as hd                     File "/home/flaryx32/homesecurity/human_detection/human_detect.py", line 63, in <module>          odapi = DetectorAPI(path_to_ckpt=model_path)  File "/home/flaryx32/homesecurity/human_detection/human_detect.py", line 17, in __init__          od_graph_def = tf.GraphDef()                AttributeError: module 'tensorflow' has no attribute 'GraphDef'

**Comment by dataplayer12** [comment]
Let me know if you face any other issues. This project supports tensorflow 1.x
I might update the project over the holidays to be more modern.
