### ISSUE TITLE
tx2_surveillance.py core dumped

### ISSUE THREAD

**Issue by JVTEAM** [dataplayer12/homesecurity#7]
Not even sure where the error is in here.  I will say the process took all 4GB of RAM and 6 Gigs of swap while running.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "jetsontx2/tx2_surveillance.py", line 150, in <module>
    main()
  File "jetsontx2/tx2_surveillance.py", line 135, in main
    _, _, _ = detect(dummy_img, tf_sess, conf_th=.3, od_type=od_type)
  File "/home/vondalej/homesecurity/jetsontx2/utils/od_utils.py", line 87, in detect
    feed_dict={tf_input: img[None, ...]})
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation Postprocessor/BatchMultiClassNonMaxSuppression/TRTEngineOp_1: Could not satisfy explicit device specification '/device:CPU:0' because no supported kernel for CPU devices is available.
Colocation Debug Info:
Colocation group had the following types and supported devices: 
Root Member(assigned_device_name_index_=-1 requested_device_name_='/device:CPU:0' assigned_device_name_='' resource_device_name_='' supported_device_types_=[GPU] possible_devices_=[]
TRTEngineOp: GPU 

Colocation members, user-requested devices, and framework assigned devices, if any:
  Postprocessor/BatchMultiClassNonMaxSuppression/TRTEngineOp_1 (TRTEngineOp) /device:CPU:0

Op: TRTEngineOp
Node attrs: use_calibration=false, fixed_input_size=true, input_shapes=[], OutT=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], precision_mode="FP16", static_engine=true, serialized_segment="ptrta\000\...00\000\000", cached_engine_batches=[], InT=[DT_FLOAT], calibration_data="", output_shapes=[], workspace_size_bytes=7965653, max_cached_engines_count=1, segment_func=Postprocessor/BatchMultiClassNonMaxSuppression/TRTEngineOp_1_native_segment[], segment_funcdef_name=""
Registered kernels:
  device='GPU'

	 [[node Postprocessor/BatchMultiClassNonMaxSuppression/TRTEngineOp_1 (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'Postprocessor/BatchMultiClassNonMaxSuppression/TRTEngineOp_1':
  File "jetsontx2/tx2_surveillance.py", line 150, in <module>
    main()
  File "jetsontx2/tx2_surveillance.py", line 125, in main
    trt_graph = load_trt_pb(pb_path)
  File "/home/vondalej/homesecurity/jetsontx2/utils/od_utils.py", line 38, in load_trt_pb
    tf.import_graph_def(trt_graph_def, name='')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 513, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/importer.py", line 517, in _import_graph_def_internal
    _ProcessNewOps(graph)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/importer.py", line 243, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3561, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3561, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3451, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

terminate called without an active exception
terminate called recursively
./launch.sh: line 43: 18873 Aborted                 (core dumped) python3 jetsontx2/tx2_surveillance.py

**Comment by dataplayer12** [comment]
Give me a day or two. Let me flash 4.4 on a nano and check this out myself. In the meantime, if you understand the problem, please share it here.

**Comment by JVTEAM** [comment]
Sounds good.  Thanks!

**Comment by dataplayer12** [comment]
I think I understood why this is happening. Basically, the fix I made yesterday (which makes the compile script work) places the NMS op on GPU, while the inference function still expects the op to be on the CPU as was the case in previous versions of tensorRT. This causes a conflict and thus the error "unable to satisfy device placement".

The fix is simple, to delete the lines of code which force a CPU placement of NMS. Please comment out lines 30-36 of the file: jetsontx2/utils/od_utils.py

I'm currently on mobile and can't edit the file but I will fix it later tonight.

**Comment by JVTEAM** [comment]
OK, i'll try this shortly.

**Comment by JVTEAM** [comment]
Fun new error.  I should mention this nano runs headless via VNC.  Not sure if that contributed to this.

INFO:__main__:starting to loop and detect
Traceback (most recent call last):
  File "jetsontx2/tx2_surveillance.py", line 150, in <module>
    main()
  File "jetsontx2/tx2_surveillance.py", line 141, in main
    loop_and_detect(stream_handler, tf_sess, 0.2, vis, od_type=od_type)
  File "jetsontx2/tx2_surveillance.py", line 78, in loop_and_detect
    img = stream_handler.read_streams()
  File "/home/vondalej/homesecurity/jetsontx2/streamutils.py", line 140, in read_streams
    self.read_queue(self.q1, 1)
  File "/home/vondalej/homesecurity/jetsontx2/streamutils.py", line 160, in read_queue
    self.framebuffer[:self.resolution[0], :self.resolution[1]] = frame
ValueError: could not broadcast input array from shape (480,640,3) into shape (360,640,3)
terminate called without an active exception
./launch.sh: line 43: 17299 Aborted                 (core dumped) python3 jetsontx2/tx2_surveillance.py

**Comment by dataplayer12** [comment]
This one is easy to understand. Your IP cameras are broadcasting at 640 x 480 (width x height) resolution, but the tx2 expects a 640 x 360 resolution. You can change this by specifying the `resolution` parameter in [this ](https://github.com/dataplayer12/homesecurity/blob/402c76bb229f321e19f3f748b7e8ac3fae471356/jetsontx2/tx2_surveillance.py#L122)line to be `(480, 640)`. The urls in the `main` function of `streamutils.py` do not need to be changed. This is only for debugging and the function is not called when running `tx2_surveillance.py`

**Comment by JVTEAM** [comment]
> This one is easy to understand. Your IP cameras are broadcasting at 640 x 480 (width x height) resolution, but the tx2 expects a 640 x 360 resolution. You can change this by specifying the `resolution` parameter in [this ](https://github.com/dataplayer12/homesecurity/blob/402c76bb229f321e19f3f748b7e8ac3fae471356/jetsontx2/tx2_surveillance.py#L122)line to be `(480, 640)`. The urls in the `main` function of `streamutils.py` do not need to be changed. This is only for debugging and the function is not called when running `tx2_surveillance.py`

Ah, so all of the camera's must have matching resolution?

**Comment by dataplayer12** [comment]
Yes, because dealing with cameras of different resolutions becomes tricky. For example, a 640 x 360 frame will arrive quickly while a 1280 x 720 frame takes 4 times as long to stream. So, if the cameras all have different resolutions, gradually they will go out of sync and the timestamp that the program shows will not be meaningful anymore. Also, computationally, resizing images is not so efficient. I could add a patch that allows for different resolutions and provides a warning about this, but I would still strongly recommend changing the settings of your camera to have the same resolution. Are you able to do that or do you absolutely need all cameras to have different resolutions?

**Comment by JVTEAM** [comment]
No I had one pi, just changed that to match the wyze cams.  It's working now,  however it's pretty slow so I'll move this to the TX2 for better performance.
Two final questions.

1. It goes full screen when running.  How do you quit or go back to the deskop?
2.  I have a smarthome that runs computers with NLP to provide alerts.  I'd like to insert a webhook in the code when it determines that it sees a human.  Where is the best place to look so I can insert that?

**Comment by dataplayer12** [comment]
1. You can press `f` to toggle the fullscreen mode and `q` to quit safely.
2. The type of detected object is found in `detect` function [here](https://github.com/dataplayer12/homesecurity/blob/06648bcb44f1b431d108444210f2297a4661d043/jetsontx2/utils/od_utils.py#L84). In fact, the nano does just what you are saying, except that it sends an email to the user with the video as an attachment. The function [determine_if_person_in](https://github.com/dataplayer12/homesecurity/blob/06648bcb44f1b431d108444210f2297a4661d043/human_detection/human_detect.py#L66) takes the name of a pre-recorded video file as an input and returns true if there is a person in the video. You could look for hints here. Class number 1 corresponds to humans, so when the output of the network has high probability for class 1, the webhook can send its alert. So, put it somewhere around line 84 in `jetsontx2/utils/od_utils.py`

**Comment by JVTEAM** [comment]
Thank you so much!  You are the best developer I've ever worked with.  I look forward to checking out your future projects!

**Comment by dataplayer12** [comment]
Thank you for the kind words and for exposing the problems in the code.
