### ISSUE TITLE
Extracting bounding box coordinates

### ISSUE THREAD

**Issue by JVTEAM** [dataplayer12/homesecurity#9]
When the program determines an object, confidence and then box location it can print this.

[67] [0.48267296] [[361   4 715 937]]

I need to extract the 361 and 4 to help determine which of the 4 boxes it is in.  Any ideas on how this could be achieved?  I've cheated a bit with the confidence by using any or all on my if statement, but I can't do that with the box.

**Comment by dataplayer12** [comment]
This should be easy. You know the resolution of the cameras and so the size of each box. So, something like `row=361//resolution[0]` and `column=4//resolution[1]` will tell you the row number and column number. (0,0) is the top left,  (1,1) is the bottom right and so on.

**Comment by JVTEAM** [comment]
I'm having trouble as the bounding boxes are a list and I can't seem to get them to extract into an integer.

**Comment by dataplayer12** [comment]
I think you almost have it. Actually, map is a good choice for this task. One can't quite map the boxes to int as you tried, but this should work:

```
boxids=map(lambda x: (x[0]>360, x[1]>640), box)
```

**Comment by JVTEAM** [comment]
> boxids=map(lambda x: (x[0]>360, x[1]>640), box)

sorry, I'm 0 for 2 on both of your suggestions.  Making that into a variable creates the same unreadable label I've been trying to translate when I print it.  

<map object at 0x7f0d3ed7f0>

Nor can I think of a way to then distinguish the 4 box ID's after that as I have created another list.  This needs to be an IF that generates a distinguishable value to compare against.

**Comment by JVTEAM** [comment]
Ok, I think I've got it... I can't test anything besides the first camera which is my test camera in the room while the others are outside and it's the middle of the night.  However, camera 1 detection seems to function.

    boxwidth = ([item[0] for item in box])
    boxheight = ([item[1] for item in box])
    boxwidth = [int(i) for i in boxwidth]
    boxheight = [int(i) for i in boxwidth]     

    #print(cls, conf, box)
    threshold = conf > 0.55
    if 1 in cls:
        if threshold.all(): 
            if last_person_time is None or datetime.now() - last_person_time > timedelta(seconds = 5):
                last_person_time = datetime.now()
                print('person detected')
                for i in boxwidth:
                    if i < 640:
                        print('detecting')
                        for i in boxheight:
                            if i <360:
                                print('Camera 1 detected')
                for i in boxwidth:
                    if i > 640:
                        print('detecting')
                        for i in boxheight:
                            if i <360:
                                print('Camera 2 detected')
                for i in boxwidth:
                    if i < 640:
                        print('detecting')
                        for i in boxheight:
                            if i >360:
                                print('Camera 3 detected') 
                for i in boxwidth:
                    if i > 640:
                        print('detecting')
                        for i in boxheight:
                            if i >360:
                                print('Camera 4 detected') 

Instead of print('camera detected') I will put the webhook to the corresponding camera that will then tell me what camera on my home intercom.  I'll prolly then do an image save as well, but this is where I wanted to be!

**Comment by dataplayer12** [comment]
It's great that you have got it working. I wonder if you will have issues with the code you pasted above, since you are reusing the same iterator variable `i` for both `boxwidth` and `boxheight`. If it does what you want, then I suppose there is no need to overthink.

**Comment by JVTEAM** [comment]
Yes, I think you are right.  However, I'm also having an issue with the fact that it's drawing other boxes with low confidence creating noise.  How do I limit drawing to above a threshold?

**Comment by JVTEAM** [comment]
Ok I changed that line above to .55 to reduce the noise.  I'll test it, but now its looking good!

    boxwidth = ([item[1] for item in box])
    boxheight = ([item[0] for item in box])
    boxwidth = [int(w) for w in boxwidth]
    boxheight = [int(h) for h in boxheight]     

    #print(cls, conf, box)
    threshold = conf > 0.55
    if 1 in cls:
        if threshold.all(): 
            if last_person_time is None or datetime.now() - last_person_time > timedelta(seconds = 5):
                last_person_time = datetime.now()


                for w in boxwidth:
                    if w < 640:
                        #print('detecting...')
                        for h in boxheight:
                            if h < 360:
                                print('Camera 1 detected')
                                print(boxwidth)
                                print(boxheight)
                for w in boxwidth:
                    if w > 640:
                        #print('detecting...')
                        for h in boxheight:
                            if h <360:
                                print('Office Camera Detected')
                                print(boxwidth)
                                print(boxheight)
                                urllib.request.urlopen('webhook1:')
                for w in boxwidth:
                    if w < 640:
                        #print('detecting...')
                        for h in boxheight:
                            if h > 360:
                                print('Side Camera Detected')
                                print(boxwidth)
                                print(boxheight)
                                urllib.request.urlopen(webhook2) 
                for w in boxwidth:
                    if w > 640:
                        #print('detecting...')
                        for h in boxheight:
                            if h > 360:
                                print('Nature Cam Detected')
                                print(boxwidth)
                                print(boxheight)
                                urllib.request.urlopen(webhook3)
